// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FirstTask2023.DAL.Models
{
    public partial class DevicePropertyTBL
    {
        [Key]
        public int Id { get; set; }
        public int? PropertyId { get; set; }
        public int? DeviceCategoryId { get; set; }

        [ForeignKey("DeviceCategoryId")]
        [InverseProperty("DevicePropertyTBL")]
        public virtual DeviceCategoryTBL DeviceCategory { get; set; }
        [ForeignKey("PropertyId")]
        [InverseProperty("DevicePropertyTBL")]
        public virtual PropertiesTBL Property { get; set; }
    }
}