// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FirstTask2023.DAL.Models
{
    public partial class DeviceCategoryTBL
    {
        public DeviceCategoryTBL()
        {
            DevicePropertyTBL = new HashSet<DevicePropertyTBL>();
            DeviceTBL = new HashSet<DeviceTBL>();
        }

        [Key]
        public int Id { get; set; }
        [StringLength(50)]
        public string Name { get; set; }

        [InverseProperty("DeviceCategory")]
        public virtual ICollection<DevicePropertyTBL> DevicePropertyTBL { get; set; }
        [InverseProperty("DeviceCategory")]
        public virtual ICollection<DeviceTBL> DeviceTBL { get; set; }
    }
}